{% set version = "0.3" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz  # [not win]
  sha256: fc961af003f53419f9f9c2efd0caf002cc2eb43fa5c076a2e44cbd9542a15b26  # [not win]

  fn: otfftw-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: ee29f72a49cf232b842c3755d96e9f57cbf836e86306de6a92fd61607748e373  # [win32 and py27]

  fn: otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 397e40e46ae24b2efbb23a16a2b1d78d79308006d279db6e6c158a04133a11b4  # [win64 and py27]

  fn: otfftw-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: 8a6e62e73b672891d62281acca2e483fb92dbe6be0d20ad64f77b0b139bbc292  # [win32 and py34]

  fn: otfftw-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: 04511b14ec1cf5bd7f30bd932031edf019a75296aac3e2f4b14f3ab122daf798  # [win64 and py34]

  fn: otfftw-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 91b3d234b398c6e2a80d124f270d906755feb18519f33f5ddd587ef4fcc8cfd5  # [win32 and py35]

  fn: otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 369392dff5451350794b72c06927c7c4ca8254e0474339741dc48e3dce5ab3db  # [win64 and py35]

build:
  number: 2

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]
    - fftw  # [not win]

  run:
    - python
    - openturns
    - fftw  # [not win]

test:
  imports:
    - otfftw

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
