travis:
  secure:
    BINSTAR_TOKEN: aexC+EOyuJ0p6ZUuaerCC4DUyreU+GaT2K/dmnJ7Rz9E3TR73LJm0G6UKbu8TjhnCigJ0io5XbXiIT4uF5CeUx8nKsvQR6AkWotEKwOXRSyS1+VbcMBbY3VecTIvXzK6lLkHcvndwvQV6d26P9z+Fk//3m7cwPOxUG1tEcvBQpxhB3ytE4WSvMvtXOA1COzze8dwVp9OVCuHtSa+mOv+65eywSiI6wpfhBEsyWvbOAedYro/lSAqitZOt36byaP5l/XIu+hGDZT+6hoYforAHmnb+OYFBw2jsln6H5HJ/UonScd0+IW1FLbE1KqPwctwKsi3eHsAG6QEnZnwoZb4iVgSIYZvFaWHhD6w2isbMZJzXsqgasGwhd8N2jAWYDZNewr/64vk05g2Gr8FhvEiTrBSeNgpoMrA8rXTS0ce0IgX/TV7u8HdYZoh1JJQ+SFGOTW/iX639miaQp4XYuVX+u54tPvP0F/V1jvHshs+CsqFP5lS3G4ZpxRQbixtDvF+VaiZZapvXneyZde5p+j6rQnHUa672ZxHUlllzes6lUs1gATI9OlAr2xkt7+6Gpg9lol1EefxwPZR7Q/+16Eo+374BsBq6cgICa6OCwVczXjyf7ydLhMewkM8WYv1bdOchb18MZ6uSuoLOdea1N23+0sQK8nqsu4pqXoNbHStdW0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
