travis:
  secure:
    BINSTAR_TOKEN: Lz70JZZnCmWKtakZ0bCVj3X0RrVhKlntuY7sv7sMdhK7JrSNb5hU5S8sElEMFQTEFu/Uhd/LJa4S0R8equtzMXuE0xJ30N+pnKgtXnvgMfCPipHE8hxk5bpGRG8esEbvIc539BWsdgV5VPltyM9WgEApQDs7G+jdAx9FZkVLIkV1cTdNKliFgYB0pvdKKoWlwsPxJy3KlIHa1iZayhE81NrbXqZkEAn8owkkcvisMygi05U3lhph04JC/6mYKIYHNxoyuksTmZeCMlX7oq101eCsMXbQ8B+vHQne1h9OgUGB/eTYRDR1phqfXwQOWa2XlTG1V/6KZ7W0W9Gns2xRg14tShQkbGQazhhNPiFU/ixSUaGjhR+Z2AzuS1a5rxQZLUwp+MvGVt5cHB2iJwnAv9qfTG3Qa7X57YOYNs++diu3AqSIIrW+8YxBRFd8qUhef+8RILjRnfCYNS6i0QUW2Osw/VfbOySet3+Dzv1/NE3czodxYOnzLjOsAn0H3H8NNhNOZ91gNAPTLhXTWqHT+YKxZkFRgMAhbUxhHy6bCS1dAwgmfWmt7RYxHA9qqfUSjszYJavm7Y9fZaVwFvgbZgFM3vPIxHTWPEmw/5r1o7wFeiWjJ1az9WrrrQYFx2ELq/PC/W8gZ/LOZTjjeC4kPInjx6ZaQvJBCgCb3Gtroz4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
