travis:
  secure:
    BINSTAR_TOKEN: MEbaf35RI8g2jvc+lUKwpAvbHm7S1fsjWz020/0C2LRGBqN2DLlr7S0NUJmIzGUA5AUstqAqOC4cQq3vDg/qmQt+vN24fpxD0AW4hpaWbmTyF2U0f/Howz40qeHz/0eKAeg0osTZjsvv2JFjZorTC931SvB7oNQLpet0olPmotKMiVP5OXBv/7YbXv4EElr6R5jsIVYhe3u7HNRS726N5jqYdRqOsHmu7ZR8RG1KStR06gVmGeFrdtl2S0A6vJv/NRRJJ9M/u/pi6PUzYskE2uMnqteQra5Bm+bDlAof1yObz/4zCuqG7aVMemOXOVrGWFOMrHcw2bBjfJwmwVzRBiB7i+5t5jmvePFn+xGs0vkpSflFVVxBe5JXjUNbHWyIMmMnMKmTUCOT+YzJ7bTHwWpQ3VrJEhM2g/XdVoammB4afCYwEqqLqQbuoE+6fbgdE6daUBDVKEcjn4YMOutaWokL9ziA7pxlSp5LYMUJfWCTtKfOq4pmmjyQ+iE9kxL8Sz7CocmOvXn1CrzIPXUusfBo63HiG0sC88E4F6YajMn9kdGsUbnH1R3kaDVJiGS2eO9mrQQ++H9AK0/tr0Y8pqzD86tVYf0Y8wu/9AF4S9g+AKHeYkTDkHQLKPh2kuEkZZdYi7GS3uGeSl8G2+c7lVe+gb3ak/9CsrOZcp4ZZT0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
